#pragma once

template <class T>
class CProxy_IGamePageEvents : public IConnectionPointImpl<T, &__uuidof( _IGamePageEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
